version: '3'
services:
    reverse-proxy:
        build: reverse-proxy
        ports:
            - 80:80
        environment:
            - NGINX_HOST=proxy01.lockorder.cc
            - NGINX_PORT=80
        networks:
            - lockorder

    eatable-ui:
        image: nginx
        volumes:
            - ./eatable-ui/html:/usr/share/nginx/html:ro
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=ui01.lockorder.cc
            - NGINX_PORT=80
        networks:
            - lockorder

    eatable-oms:
        build: eatable-oms
        volumes:
            - ./eatable-oms/config:/config
            - ./logs/:/logs
            - ./eatable-oms/files/menu:/files/menu
        ports:
            - 6080:6080
        environment:
            - JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"
        networks:
            - lockorder

    db-postgres:
        image: postgres
        volumes:
            - /opt/lockorder/pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

networks:
    lockorder:
